export const countries = [
  { name: "Algeria", code: "DZ", continent: "Africa" },
  { name: "Angola", code: "AO", continent: "Africa" },
  { name: "Benin", code: "BJ", continent: "Africa" },
  { name: "Botswana", code: "BW", continent: "Africa" },
  { name: "Burkina Faso", code: "BF", continent: "Africa" },
  { name: "Burundi", code: "BI", continent: "Africa" },
  { name: "Cape Verde", code: "CV", continent: "Africa" },
  { name: "Cameroon", code: "CM", continent: "Africa" },
  { name: "Central African Republic", code: "CF", continent: "Africa" },
  { name: "Chad", code: "TD", continent: "Africa" },
  { name: "Comoros", code: "KM", continent: "Africa" },
  { name: "Congo", code: "CG", continent: "Africa" },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    continent: "Africa",
  },
  { name: "Cote D'Ivoire", code: "CI", continent: "Africa" },
  { name: "Djibouti", code: "DJ", continent: "Africa" },
  { name: "Egypt", code: "EG", continent: "Africa" },
  { name: "Equatorial Guinea", code: "GQ", continent: "Africa" },
  { name: "Eritrea", code: "ER", continent: "Africa" },
  { name: "Ethiopia", code: "ET", continent: "Africa" },
  { name: "Gabon", code: "GA", continent: "Africa" },
  { name: "Gambia", code: "GM", continent: "Africa" },
  { name: "Ghana", code: "GH", continent: "Africa" },
  { name: "Guinea", code: "GN", continent: "Africa" },
  { name: "Guinea-Bissau", code: "GW", continent: "Africa" },
  { name: "Kenya", code: "KE", continent: "Africa" },
  { name: "Lesotho", code: "LS", continent: "Africa" },
  { name: "Liberia", code: "LR", continent: "Africa" },
  { name: "Libyan Arab Jamahiriya", code: "LY", continent: "Africa" },
  { name: "Madagascar", code: "MG", continent: "Africa" },
  { name: "Malawi", code: "MW", continent: "Africa" },
  { name: "Mali", code: "ML", continent: "Africa" },
  { name: "Morocco", code: "MA", continent: "Africa" },
  { name: "Mozambique", code: "MZ", continent: "Africa" },
  { name: "Namibia", code: "NA", continent: "Africa" },
  { name: "Niger", code: "NE", continent: "Africa" },
  { name: "Nigeria", code: "NG", continent: "Africa" },
  { name: "RWANDA", code: "RW", continent: "Africa" },
  { name: "Sao Tome and Principe", code: "ST", continent: "Africa" },
  { name: "Senegal", code: "SN", continent: "Africa" },
  { name: "Seychelles", code: "SC", continent: "Africa" },
  { name: "Sierra Leone", code: "SL", continent: "Africa" },
  { name: "Somalia", code: "SO", continent: "Africa" },
  { name: "South Africa", code: "ZA", continent: "Africa" },
  { name: "Sudan", code: "SD", continent: "Africa" },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    continent: "Africa",
  },
  { name: "Togo", code: "TG", continent: "Africa" },
  { name: "Tunisia", code: "TN", continent: "Africa" },
  { name: "Uganda", code: "UG", continent: "Africa" },
  { name: "Zambia", code: "ZM", continent: "Africa" },
  { name: "Zimbabwe", code: "ZW", continent: "Africa" },
  { name: "Mauritania", code: "MR", continent: "Africa" },
  { name: "Mauritius", code: "MU", continent: "Africa" },
  { name: "Mayotte", code: "YT", continent: "Africa" },
  { name: "Reunion", code: "RE", continent: "Africa" },
  { name: "Saint Helena", code: "SH", continent: "Africa" },
  { name: "Swaziland", code: "SZ", continent: "Africa" },
  { name: "Western Sahara", code: "EH", continent: "Africa" },

  { name: "Afghanistan", code: "AF", continent: "Asia" },
  { name: "Armenia", code: "AM", continent: "Asia" },
  { name: "Azerbaijan", code: "AZ", continent: "Asia" },
  { name: "Bahrain", code: "BH", continent: "Asia" },
  { name: "Bangladesh", code: "BD", continent: "Asia" },
  { name: "Bhutan", code: "BT", continent: "Asia" },
  { name: "Brunei Darussalam", code: "BN", continent: "Asia" },
  { name: "Cambodia", code: "KH", continent: "Asia" },
  { name: "China", code: "CN", continent: "Asia" },
  { name: "Georgia", code: "GE", continent: "Asia" },
  { name: "India", code: "IN", continent: "Asia" },
  { name: "Indonesia", code: "ID", continent: "Asia" },
  { name: "Iran, Islamic Republic Of", code: "IR", continent: "Asia" },
  { name: "Iraq", code: "IQ", continent: "Asia" },
  { name: "Israel", code: "IL", continent: "Asia" },
  { name: "Japan", code: "JP", continent: "Asia" },
  { name: "Jordan", code: "JO", continent: "Asia" },
  { name: "Kazakhstan", code: "KZ", continent: "Asia" },
  {
    name: "Korea, Democratic People'S Republic of",
    code: "KP",
    continent: "Asia",
  },
  { name: "Korea, Republic of", code: "KR", continent: "Asia" },
  { name: "Kuwait", code: "KW", continent: "Asia" },
  { name: "Kyrgyzstan", code: "KG", continent: "Asia" },
  {
    name: "Lao People'S Democratic Republic",
    code: "LA",
    continent: "Asia",
  },
  { name: "Malaysia", code: "MY", continent: "Asia" },
  { name: "Mongolia", code: "MN", continent: "Asia" },
  { name: "Myanmar", code: "MM", continent: "Asia" },
  { name: "Nepal", code: "NP", continent: "Asia" },
  { name: "Oman", code: "OM", continent: "Asia" },
  { name: "Pakistan", code: "PK", continent: "Asia" },
  {
    name: "Palestinian Territory, Occupied",
    code: "PS",
    continent: "Asia",
  },
  { name: "Philippines", code: "PH", continent: "Asia" },
  { name: "Qatar", code: "QA", continent: "Asia" },
  { name: "Saudi Arabia", code: "SA", continent: "Asia" },
  { name: "Singapore", code: "SG", continent: "Asia" },
  { name: "Sri Lanka", code: "LK", continent: "Asia" },
  { name: "Syrian Arab Republic", code: "SY", continent: "Asia" },
  { name: "Taiwan, Province of China", code: "TW", continent: "Asia" },
  { name: "Tajikistan", code: "TJ", continent: "Asia" },
  { name: "Thailand", code: "TH", continent: "Asia" },
  { name: "Timor-Leste", code: "TL", continent: "Asia" },
  { name: "Turkmenistan", code: "TM", continent: "Asia" },
  { name: "United Arab Emirates", code: "AE", continent: "Asia" },
  { name: "Uzbekistan", code: "UZ", continent: "Asia" },
  { name: "VietNam", code: "VN", continent: "Asia" },
  { name: "Hong Kong", code: "HK", continent: "Asia" },
  { name: "Lebanon", code: "LB", continent: "Asia" },
  { name: "Macao", code: "MO", continent: "Asia" },
  { name: "Maldives", code: "MV", continent: "Asia" },
  { name: "Yemen", code: "YE", continent: "Asia" },
  { name: "Christmas Island", code: "CX", continent: "Asia" },
  { name: "Cocos (Keeling) Islands", code: "CC", continent: "Asia" },

  { name: "Albania", code: "AL", continent: "Europe" },
  { name: "AndorrA", code: "AD", continent: "Europe" },
  { name: "Austria", code: "AT", continent: "Europe" },
  { name: "Belarus", code: "BY", continent: "Europe" },
  { name: "Belgium", code: "BE", continent: "Europe" },
  { name: "Bosnia and Herzegovina", code: "BA", continent: "Europe" },
  { name: "Bulgaria", code: "BG", continent: "Europe" },
  { name: "Croatia", code: "HR", continent: "Europe" },
  { name: "Cyprus", code: "CY", continent: "Europe" },
  { name: "Czech Republic", code: "CZ", continent: "Europe" },
  { name: "Denmark", code: "DK", continent: "Europe" },
  { name: "Estonia", code: "EE", continent: "Europe" },
  { name: "Finland", code: "FI", continent: "Europe" },
  { name: "France", code: "FR", continent: "Europe" },
  { name: "Germany", code: "DE", continent: "Europe" },
  { name: "Greece", code: "GR", continent: "Europe" },
  { name: "Hungary", code: "HU", continent: "Europe" },
  { name: "Iceland", code: "IS", continent: "Europe" },
  { name: "Ireland", code: "IE", continent: "Europe" },
  { name: "Italy", code: "IT", continent: "Europe" },
  { name: "Latvia", code: "LV", continent: "Europe" },
  { name: "Liechtenstein", code: "LI", continent: "Europe" },
  { name: "Lithuania", code: "LT", continent: "Europe" },
  { name: "Luxembourg", code: "LU", continent: "Europe" },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    continent: "Europe",
  },
  { name: "Malta", code: "MT", continent: "Europe" },
  { name: "Moldova, Republic of", code: "MD", continent: "Europe" },
  { name: "Monaco", code: "MC", continent: "Europe" },
  { name: "Netherlands", code: "NL", continent: "Europe" },
  { name: "Norway", code: "NO", continent: "Europe" },
  { name: "Poland", code: "PL", continent: "Europe" },
  { name: "Portugal", code: "PT", continent: "Europe" },
  { name: "Romania", code: "RO", continent: "Europe" },
  { name: "San Marino", code: "SM", continent: "Europe" },
  { name: "Serbia and Montenegro", code: "CS", continent: "Europe" },
  { name: "Slovakia", code: "SK", continent: "Europe" },
  { name: "Slovenia", code: "SI", continent: "Europe" },
  { name: "Spain", code: "ES", continent: "Europe" },
  { name: "Switzerland", code: "CH", continent: "Europe" },
  { name: "Russian Federation", code: "RU", continent: "Europe" },
  { name: "Turkey", code: "TR", continent: "Europe" },
  { name: "Ukraine", code: "UA", continent: "Europe" },
  { name: "United Kingdom", code: "GB", continent: "Europe" },
  { name: "Åland Islands", code: "AX", continent: "Europe" },
  { name: "Faroe Islands", code: "FO", continent: "Europe" },
  { name: "Gibraltar", code: "GI", continent: "Europe" },
  { name: "Guernsey", code: "GG", continent: "Europe" },
  {
    name: "Holy See (Vatican City State)",
    code: "VA",
    continent: "Europe",
  },
  { name: "Isle of Man", code: "IM", continent: "Europe" },
  { name: "Jersey", code: "JE", continent: "Europe" },
  { name: "Svalbard and Jan Mayen", code: "SJ", continent: "Europe" },
  { name: "Sweden", code: "SE", continent: "Europe" },

  { name: "Argentina", code: "AR", continent: "South America" },
  { name: "Bolivia", code: "BO", continent: "South America" },
  { name: "Brazil", code: "BR", continent: "South America" },
  { name: "Chile", code: "CL", continent: "South America" },
  { name: "Colombia", code: "CO", continent: "South America" },
  { name: "Ecuador", code: "EC", continent: "South America" },
  { name: "Guyana", code: "GY", continent: "South America" },
  { name: "Paraguay", code: "PY", continent: "South America" },
  { name: "Peru", code: "PE", continent: "South America" },
  { name: "Uruguay", code: "UY", continent: "South America" },
  { name: "Venezuela", code: "VE", continent: "South America" },
  { name: "Suriname", code: "SR", continent: "South America" },
  { name: "French Guiana", code: "GF", continent: "South America" },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    continent: "South America",
  },
  { name: "French Polynesia", code: "PF", continent: "South America" },

  { name: "Antigua and Barbuda", code: "AG", continent: "North America" },
  { name: "Barbados", code: "BB", continent: "North America" },
  { name: "Belize", code: "BZ", continent: "North America" },
  { name: "Canada", code: "CA", continent: "North America" },
  { name: "Costa Rica", code: "CR", continent: "North America" },
  { name: "Cuba", code: "CU", continent: "North America" },
  { name: "Dominican Republic", code: "DO", continent: "North America" },
  { name: "El Salvador", code: "SV", continent: "North America" },
  { name: "Guatemala", code: "GT", continent: "North America" },
  { name: "Haiti", code: "HT", continent: "North America" },
  { name: "Honduras", code: "HN", continent: "North America" },
  { name: "Jamaica", code: "JM", continent: "North America" },
  { name: "Mexico", code: "MX", continent: "North America" },
  { name: "Nicaragua", code: "NI", continent: "North America" },
  { name: "Panama", code: "PA", continent: "North America" },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    continent: "North America",
  },
  { name: "Saint Lucia", code: "LC", continent: "North America" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    continent: "North America",
  },
  { name: "Trinidad and Tobago", code: "TT", continent: "North America" },
  { name: "Wallis and Futuna", code: "WF", continent: "North America" },
  { name: "Anguilla", code: "AI", continent: "North America" },
  { name: "Bahamas", code: "BS", continent: "North America" },
  { name: "Bermuda", code: "BM", continent: "North America" },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    continent: "North America",
  },
  { name: "Cayman Islands", code: "KY", continent: "North America" },
  { name: "Dominica", code: "DM", continent: "North America" },
  { name: "Greenland", code: "GL", continent: "North America" },
  { name: "Martinique", code: "MQ", continent: "North America" },
  { name: "Montserrat", code: "MS", continent: "North America" },
  {
    name: "Netherlands Antilles",
    code: "AN",
    continent: "North America",
  },
  { name: "Puerto Rico", code: "PR", continent: "North America" },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    continent: "North America",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    continent: "North America",
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    continent: "North America",
  },
  {
    name: "Virgin Islands, U.S.",
    code: "VI",
    continent: "North America",
  },
  { name: "Aruba", code: "AW", continent: "North America" },
  { name: "Grenada", code: "GD", continent: "North America" },
  { name: "Guadeloupe", code: "GP", continent: "North America" },

  { name: "United States", code: "US", continent: "North America" },
  { name: "Australia", code: "AU", continent: "Oceania" },
  { name: "Fiji", code: "FJ", continent: "Oceania" },
  { name: "Marshall Islands", code: "MH", continent: "Oceania" },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    continent: "Oceania",
  },
  { name: "Nauru", code: "NR", continent: "Oceania" },
  { name: "New Zealand", code: "NZ", continent: "Oceania" },
  { name: "Palau", code: "PW", continent: "Oceania" },
  { name: "Papua New Guinea", code: "PG", continent: "Oceania" },
  { name: "Samoa", code: "WS", continent: "Oceania" },
  { name: "Solomon Islands", code: "SB", continent: "Oceania" },
  { name: "Tonga", code: "TO", continent: "Oceania" },
  { name: "Tuvalu", code: "TV", continent: "Oceania" },
  { name: "Vanuatu", code: "VU", continent: "Oceania" },
  { name: "American Samoa", code: "AS", continent: "Oceania" },
  { name: "Cook Islands", code: "CK", continent: "Oceania" },
  { name: "Kiribati", code: "KI", continent: "Oceania" },
  { name: "New Caledonia", code: "NC", continent: "Oceania" },
  { name: "Niue", code: "NU", continent: "Oceania" },
  { name: "Norfolk Island", code: "NF", continent: "Oceania" },
  { name: "Tokelau", code: "TK", continent: "Oceania" },
  { name: "Guam", code: "GU", continent: "Oceania" },
  { name: "Northern Mariana Islands", code: "MP", continent: "Oceania" },
  { name: "Pitcairn", code: "PN", continent: "Oceania" },

  { name: "Antarctica", code: "AQ", continent: "Antarctica" },
  { name: "Bouvet Island", code: "BV", continent: "Antarctica" },
  {
    name: "French Southern Territories",
    code: "TF",
    continent: "Antarctica",
  },
  {
    name: "Heard Island and Mcdonald Islands",
    code: "HM",
    continent: "Antarctica",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    continent: "Antarctica",
  },
];
